version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "visitor-count-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b97dydpd61rb"
s3_prefix = "visitor-count-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["AuthFunction=018535342366.dkr.ecr.eu-west-1.amazonaws.com/visitor-count-app", "VisitorCountFunction=018535342366.dkr.ecr.eu-west-1.amazonaws.com/visitor-count-app"]
