AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  visitor-count

  Stack for tracking visitor count
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        AllowOrigin: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt AuthFunction.Arn
            Identity:
              ReauthorizeEvery: 0
              QueryStrings:
                - time
                - hash
              Header:
                - Authorization
              
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          ThrottlingBurstLimit: 5
          ThrottlingRateLimit: 2
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./auth
      Dockerfile: Dockerfile
  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        VisitorCount:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /visitor-count
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName: visitor_count
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./app
      Dockerfile: Dockerfile

      
  VisitorCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
      SSESpecification:
        SSEEnabled: true
      TableName: visitor_count

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor-count/"
  VisitorCountFunction:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt VisitorCountFunction.Arn
  VisitorCountFunctionIamRole:
    Description: "Implicit IAM Role created for Visitor Count function"
    Value: !GetAtt VisitorCountFunctionRole.Arn
