AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  visitor-count

  Sample SAM Template for visitor-count
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          ThrottlingBurstLimit: 5
          ThrottlingRateLimit: 2
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./auth
      Dockerfile: Dockerfile
  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        VisitorCount:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /visitor-count
            Method: post
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./app
      Dockerfile: Dockerfile
    Policies:
      - AmazonDynamoDBFullAccess
      
  VisitorCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
      SSESpecification:
        SSEEnabled: true
      TableName: visitor_count

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor-count/"
  VisitorCountFunction:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt VisitorCountFunction.Arn
  VisitorCountFunctionIamRole:
    Description: "Implicit IAM Role created for Visitor Count function"
    Value: !GetAtt VisitorCountFunctionRole.Arn
